# Generated by Django 4.1.7 on 2023-03-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name_plural': 'Links'},
        ),
        migrations.AddField(
            model_name='links',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
