# Generated by Django 4.1.7 on 2023-03-06 01:08

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_links_options_links_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='hash_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='links',
            name='time',
            field=models.IntegerField(default=300, help_text='Seconds', validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
