# Generated by Django 4.1.7 on 2023-03-06 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_links_hash_link_alter_links_date_creation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='hash_link',
            new_name='expiration_link',
        ),
    ]
