# Generated by Django 4.1.7 on 2023-03-06 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_rename_image_other_image_image_custom'),
        ('links', '0004_rename_hash_link_links_expiration_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='user',
        ),
        migrations.AlterField(
            model_name='links',
            name='expiration_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='original_image', to='images.image'),
        ),
    ]
