# Generated by Django 4.1.7 on 2023-03-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0008_links_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='image',
        ),
    ]
