# Generated by Django 4.1.7 on 2023-03-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0010_links_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='time',
            field=models.IntegerField(default=300, help_text='Seconds'),
        ),
    ]
