# Generated by Django 4.1.7 on 2023-03-02 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('images', '0002_image_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='profiles.profile'),
        ),
    ]
