# Generated by Django 4.1.7 on 2023-03-03 17:43

import apps.images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_image_200_image_image_400_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_200',
            field=models.ImageField(blank=True, null=True, upload_to=apps.images.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_400',
            field=models.ImageField(blank=True, null=True, upload_to=apps.images.models.user_directory_path),
        ),
    ]
