# Generated by Django 4.1.7 on 2023-03-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_image_image_200_alter_image_image_400_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='plan',
        ),
    ]
