# Generated by Django 4.1.7 on 2023-03-04 09:59

import apps.images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_alter_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.images.models.user_directory_path),
        ),
    ]
