# Generated by Django 4.1.7 on 2023-03-04 10:58

import apps.images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_other',
            field=models.ImageField(blank=True, null=True, upload_to=apps.images.models.user_directory_path_custom),
        ),
    ]
