# Generated by Django 4.1.7 on 2023-03-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_image_image_other'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_other',
            new_name='image_custom',
        ),
    ]
