# Generated by Django 4.1.7 on 2023-03-01 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_basic', models.BooleanField(default=False, help_text='Basic plan?', verbose_name='Basic')),
                ('is_premium', models.BooleanField(default=False, help_text='Premium plan?', verbose_name='Premium')),
                ('is_enterprise', models.BooleanField(default=False, help_text='Enterprise plan?', verbose_name='Enterprise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
