# Generated by Django 4.1.7 on 2023-03-03 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_basic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_enterprise',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_premium',
        ),
        migrations.AddField(
            model_name='profile',
            name='tier',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Enterprise'), ('CUSTOM', 'Custom')], default='BASIC', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
