# Generated by Django 4.1.7 on 2023-03-04 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom',
            name='custom_choice',
        ),
        migrations.AddField(
            model_name='custom',
            name='resolution',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='custom', to='profiles.custom'),
        ),
    ]
