# Generated by Django 4.1.7 on 2023-03-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_custom_custom_choice_custom_resolution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='custom_choice',
            new_name='custom',
        ),
    ]
