# Generated by Django 4.1.7 on 2023-03-04 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_custom_choice_profile_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='custom',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom', to='profiles.custom'),
        ),
    ]
