# Generated by Django 4.1.7 on 2023-03-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_profile_custom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='custom',
            new_name='custom_resolution',
        ),
    ]
