# Generated by Django 4.1.7 on 2023-03-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_rename_custom_profile_custom_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='resolution',
            field=models.IntegerField(default=1000),
        ),
    ]
