# Generated by Django 4.1.7 on 2023-03-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_custom_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='resolution',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='custom_resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.custom'),
        ),
    ]
